pizzas/urls.py
"""Defines URL patterns for pizza livrable"""

from django.urls import path

from . import views

app_name = 'recette_pizza'
urlpatterns = [
	# Home page
	path('',views.index, name='index'),
	# Définition de l'URL de la page contenant les noms de pizzas
	path('pizzas/', views.pizzas, name='pizzas'),
	#URL de la page des garnitures de pizzas
	path('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #Home page 
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),

]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):# Modèle qui permet de tenir les valeurs des noms
	name = models.CharField(max_length=200) #Field made of characters with a limit 
	date_added = models.DateTimeField(auto_now_add=True)#Field which record
														#date and time
	def __str__(self):#Attribute used by default when there is information about a topic
		"""Return a string representation of the model."""
		return self.name

class Topping(models.Model):
	pizza = models.ForeignKey('Pizza', on_delete = models.CASCADE)#Connect to each entry to a specific topic
	date_added = models.DateTimeField(auto_now_add=True)#Present entries in chronological order
	topping_list = models.TextField() #Field made of characters with a limit 

	class Meta:
		verbose_name_plural = 'Topping List'

	def __str__(self):#Attribute used by default when there is information about a topic
		"""Return a string representation of the model."""
		return self.topping_list

pizzas/views.py
"""Prend les données liés aux noms de pizzas et garnitures pour générer une page et les renvoie au navigateur"""

from django.shortcuts import render
from .models import Pizza, Topping #import du modèle Pizza

# Create your views here.
def index(request): 
	"""The home page for Pizza livrable."""
	return render(request, 'pizzas/index.html')

def pizzas(request):
	"""Show all pizzas names."""
	pizzas = Pizza.objects.order_by('?')#demande des objets Pizzas et triage chronologique
	context = {'pizzas': pizzas}#accès aux noms de pizzas et envoi vers le template
	return render(request, 'pizzas/pizzas.html', context)#envoie des noms de pizzas vers le template

def pizza(request, pizza_id):
	"""Montre le nom de la pizza et tout sa garniture."""
	pizza = Pizza.objects.get(id=pizza_id)#Reprend le nom de pizza
	toppings = pizza.topping_set.order_by('-date_added')
	context = {'pizza': pizza, 'toppings':toppings}
	return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'recette_pizza:index' %}">Pizza Livrable</a> -
	<a href="{% url 'recette_pizza:pizzas' %}">Noms de pizzas</a> 
</p> <!--- génère les urls définit dans urls.py avec le nom 'index' et 'noms de pizzas'---> 

{% block content %}{% endblock content %}  

pizzas/templates/pizzas/index.html
<!--- Template enfant qui explique le rôle de notre projet --->

{% extends "pizzas/base.html" %} <!--- Hérite du modèle parent base.html--->

{% block content %}
<p> Pizza Livrable allow to take the pizza name and his toppings</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizza : {{ pizza }}</p>

<p>Garnitures:</p>
<ul>
	{% for topping in toppings %}
		<li>
			<p>{{ topping.date_added|date:'M d, Y H:i' }}</p> <!-- Horodatage des garnitures au format Mois jour, Année heure ---> 
			<p>{{ topping.topping_list|linebreaks }}</p><!--- Affichage des textes des garnitures avec des sauts de lignes compris par les navigateurs web --->
		</li>
	{% empty %}
		<li>Il n'y a pas encore de garniture mentionnés pour cette pizza encore.</li>
	{% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}

	<p>Noms de pizzas</p>

	<ul> <!--- Liste désordonnées de pizzas --->
		{% for pizza in pizzas %} <!--- Transformation de la liste noms_pizzas en listes à puce --->
			<li>
				 <a href ="{% url 'recette_pizza:pizza' pizza.id %}"> {{ pizza }}</a>
			</li>
			{% empty %}<!--- Si rien dans la liste, afficher ce message --->
			<li>Il n'y a pas encore de noms de pizzas ajoutées.</li>
		{% endfor %}
	</ul>

{% endblock content %}